# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: NSXSOFT
email: nsxsoft@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  IT Systems Engineer, Systems Developer, Embedded Systems Engineer and Open Source Geek - Unix, Redhat, Ubuntu, F5, Networking and Security
baseurl: "" # the subpath of your site, e.g. /blog

url: "https://www.nsxsoft.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: nsxsoft
github_username:  nsxsoft

navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "https://deanattali.com"

#####################################################
# Build settings
# Output options (more information on Jekyll's site)
#####################################################

timezone: "America/Toronto"
markdown: kramdown
highlighter: rouge
#permalink: /:year-:month-:day-:title/
paginate: 5
kramdown:
  input: GFM

theme: minima

gems:
  - jekyll-feed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-admin

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"

